# Deploys to the backend
name: Backend Deploy

on:
  push:
    branches:
      - 'main'

# Only one deploy at a time to not mess up the terraform state
concurrency:
  group: backend-deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - run: |
        ./gradlew :terraform:apply
        ./gradlew :service:bumpCloudRunRevision

      env:
        GOOGLE_APPLICATION_CREDENTIALS_CONTENT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_CONTENT }}
        TF_VAR_gandi_access_token: ${{ secrets.TF_VAR_gandi_access_token }}
